site_name: Alex Merck's OMS Cybersecurity Practicum
site_url: https://amerck_oms_practicum.readthedocs.io
theme: readthedocs
docs_dir: docs
nav:
    - index.md
    - Architecture: architecture.md
    - Development Environment: dev_environ.md
    - Training Tests: training_tests.md
    - Scripts: scripts.md
    - ML Notes: ml_notes.md
    - Timeline: timeline.md
    - References: references.md
