services:
  jupyter:
    build:
      context: jupyter
    ports:
      - 8889:8888
    volumes:
      - ./jupyter-data:/home/jovyan/work
    command: start-notebook.py --NotebookApp.token='changeme'


  neo4j:
    image: neo4j:latest
    volumes:
      - ./neo4j/logs:/logs
      - ./neo4j/config:/config
      - ./neo4j/data:/data
      - ./neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/changeme
    ports:
      - "127.0.0.1:7474:7474"
      - "127.0.0.1:7687:7687"
    restart: always
    user: '1000'
    group_add:
      - '1000'


  qdrant:
    image: qdrant/qdrant:v1.14.1
    container_name: qdrant
    ports:
      - "127.0.0.1:6333:6333"      # REST and gRPC API
      - "127.0.0.1:6334:6334"      # WebSocket (optional, for future use)
    volumes:
      - ./qdrant_storage:/qdrant/storage
#    environment:
#      QDRANT__SERVICE__API_KEY: your-optional-api-key  # Optional: for API protection